name: Build libheif
run-name: ${{ github.actor }} is building libheif
on:
    push:
        branches:
            - cyro/feat/libheif-build-actions

# on: workflow_dispatch

jobs:
    Build-Linux:
        runs-on: ubuntu-latest
        
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4

            - run: echo "${{ github.repository }} cloned"
            
            - name: "[Debug] List directory contents"
              run: ls -lah

            - name: Make build directory
              run: mkdir build

            - name: Create output directory variable
              id: buildoutput
              run: echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

            - name: Configure CMake
              working-directory: ${{ steps.buildoutput.outputs.build-output-dir }}
              run: cmake --preset=release-noplugins ..
            
            - name: "[Debug] List build config"
              working-directory: ${{ steps.buildoutput.outputs.build-output-dir }}
              run: ls -lah

            - name: Build libheif
              working-directory: ${{ steps.buildoutput.outputs.build-output-dir }}
              run: make
            
            - name: "[Debug] List build directory contents again"
              working-directory: ${{ steps.buildoutput.outputs.build-output-dir }}
              run: ls -lah
            
            - name: "[Debug] List libheif directory"
              working-directory: ${{ steps.buildoutput.outputs.build-output-dir }}
              run: "ls -lah ./libheif"
            
            - name: Archive and put a pretty bow on it
              uses: actions/upload-artifact@v4
              with:
                name: libheif
                path: ${{ steps.buildoutput.outputs.build-output-dir }}/libheif
    
    Build-Windows:
        runs-on: windows-latest

        steps:
            - name: Check out repository code
              uses: actions/checkout@v4

            - run: echo "${{ github.repository }} cloned"
            
            - name: "[Debug] List directory contents"
              run: dir

            - name: Make build directory
              run: mkdir build

            - name: Create output directory variable
              id: buildoutput
              run: echo "build-output-dir=${{ github.workspace }}/build" >> "$Env:GITHUB_OUTPUT"

            - name: Configure CMake
              working-directory: ${{ steps.buildoutput.outputs.build-output-dir }}
              run: cmake --preset=release-noplugins ..
            
            - name: "[Debug] List build config"
              working-directory: ${{ steps.buildoutput.outputs.build-output-dir }}
              run: dir

            - name: Build libheif
              working-directory: ${{ steps.buildoutput.outputs.build-output-dir }}
              run: cmake --build . --config Release
            
            - name: "[Debug] List build directory contents again"
              working-directory: ${{ steps.buildoutput.outputs.build-output-dir }}
              run: dir
            
            - name: "[Debug] List libheif directory"
              working-directory: ${{ steps.buildoutput.outputs.build-output-dir }}
              run: dir "./libheif/Release"
            
            - name: Archive and put a pretty bow on it
              uses: actions/upload-artifact@v4
              with:
                name: libheif
                path: ${{ steps.buildoutput.outputs.build-output-dir }}/libheif/Release

