name: Build libheif
run-name: ${{ github.actor }} is building libheif
on:
    push:
        branches:
            - cyro/feat/libheif-build-actions

# on: workflow_dispatch

jobs:
    Build-Linux:
        runs-on: ubuntu-latest
        
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4

            - run: echo "${{ github.repository }} cloned"

            - name: Make build directory
              run: mkdir build

            - name: Create output directory variable
              id: buildoutput
              run: echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

            - name: Configure CMake
              working-directory: ${{ steps.buildoutput.outputs.build-output-dir }}
              run: cmake --preset=release-noplugins ..

            - name: Build libheif
              working-directory: ${{ steps.buildoutput.outputs.build-output-dir }}
              run: make
            
            - name: Archive and put a pretty bow on it
              uses: actions/upload-artifact@v4
              with:
                name: libheif-linux
                path: ${{ steps.buildoutput.outputs.build-output-dir }}/libheif
    
    Build-Windows:
        runs-on: windows-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4

            - run: echo "${{ github.repository }} cloned"

            - name: Make build directory
              run: mkdir build

            - name: Create output directory variable
              id: buildoutput
              run: echo "build-output-dir=${{ github.workspace }}/build" >> "$Env:GITHUB_OUTPUT"

            - uses: ilammy/setup-nasm@v1
            - uses: seanmiddleditch/gha-setup-ninja@master
            - name: Grab AOM for basic AVIF encoding/decoding
              working-directory: ${{ github.workspace }}/third-party
              run: |
                git clone -b v3.9.0 --depth 1 https://aomedia.googlesource.com/aom

                cd aom

                cmake -S . -B build.libavif -G Ninja -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/third-party/aom/dist" -DCMAKE_BUILD_TYPE=Release -DENABLE_DOCS=0 -DENABLE_EXAMPLES=0 -DENABLE_TESTDATA=0 -DENABLE_TESTS=0 -DENABLE_TOOLS=0
                ninja -C build.libavif
                ninja -C build.libavif install

                cd ..

            - name: Configure CMake
              working-directory: ${{ steps.buildoutput.outputs.build-output-dir }}
              run: |
                cmake --preset=release-noplugins .. -DAOM_INCLUDE_DIR="${{ github.workspace }}\third-party\aom" -DAOM_LIBRARY="${{ github.workspace }}\third-party\aom\dist\lib\libaom.lib"

            - name: Build libheif
              working-directory: ${{ steps.buildoutput.outputs.build-output-dir }}
              run: cmake --build . --config Release
            
            - name: Archive and put a pretty bow on it
              uses: actions/upload-artifact@v4
              with:
                name: libheif-windows
                path: ${{ steps.buildoutput.outputs.build-output-dir }}/libheif/Release

