name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    push:
        branches:
            - cyro/feat/libheif-build-actions

jobs:
    Build-Libheif-All-Platforms:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
              
            - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

            - name: "CD into repo directory"
              run: |
                cd ${{ github.workspace }}

            - name: "Make build directory"
              run: mkdir build

            - name: Create output directory variable
              run: echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

            - name: CD into build directory
              run: cd build

            - name: Configure CMake
              run: cmake --preset=release-noplugins ..

            - name: Build libheif
              run: make

            - run: 
