name: Build libheif
run-name: ${{ github.actor }} is building libheif
on:
    push:
        branches:
            - cyro/feat/libheif-build-actions

jobs:
    Build-Libheif-All-Platforms:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4

            - run: echo "The ${{ github.repository }} cloned"

            - name: "CD into repo directory"
              run: |
                cd ${{ github.workspace }}
            
            - name: "[Debug] List directory contents"
              run: "ls -lah"

            - name: Make build directory
              run: mkdir build

            - name: Create output directory variable
              id: buildoutput
              run: echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

            - name: CD into build directory
              run: cd build

            - name: Configure CMake
              run: cmake --preset=release-noplugins ${{ github.workspace }}

            - name: Build libheif
              run: make -j$(grep -c processor /proc/cpuinfo)
            
            - name: "[Debug] List build directory contents again"
              run: ls -lah
            
            - name: "[Debug] List libheif directory"
              run: ls -lah ./libheif
            
            - name: Archive and put a pretty bow on it
              uses: actions/upload-artifact@v4
              with:
                name: libheif
                path: ${{ steps.buildoutput.outputs.build-output-dir }}
